### ISSUE TITLE
可不可以请作者写一个手动部署的方式

### ISSUE THREAD

**Issue by cakexxx** [GangZhuo/cf-doh#2]
您好，我有一个cf worker 想充分利用它的功能；我在github搜索到您这个项目感觉有些兴趣，但是您的部署方式还需要安装wrangler，是不是有一种方式可以直接创建worker复制粘贴呢？另外这个能不能实现DoH的一些广告过滤功能呢？我对编程不了解，希望得到您的解答，谢谢！

**Comment by GangZhuo** [comment]
这是从我的 worker 中复制出来的代码： https://github.com/GangZhuo/cf-doh/blob/master/dist/cf-doh-min.js ，你可以放到自己的 worker 中试试。

目前仅是把请求转发到上游 DOH (Google DOH)，不支持广告过滤功能。

**Comment by cakexxx** [comment]
> 这是从我的 worker 中复制出来的代码： https://github.com/GangZhuo/cf-doh/blob/master/dist/cf-doh-min.js ，你可以放到自己的 worker 中试试。
> 
> 目前仅是把请求转发到上游 DOH (Google DOH)，不支持广告过滤功能。

好像不能成功耶……

**Comment by GangZhuo** [comment]
See https://github.com/GangZhuo/cf-doh#%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2
